// RootLayout.tsx
import React from "react";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import { Providers } from "./redux/provider"; // Import Providers from correct path

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers> {/* Use Providers component here */}
      </body>
    </html>
  );
};

export default RootLayout;
